site_name: ukp_github
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: ukp_github
      handlers:
        python:
          options:
            docstring_style: numpy